var database = [
    {
        id: "0", songs: "阴天", name: "莫文蔚", src: "music/阴天.mp3", alltime:"04:02", photo: "images/mww.jpg", lyrics: [
        {time: "00:02", lyric: "阴天"},
        {time: "00:04", lyric: "莫文蔚"},
        {time: "00:06", lyric: "作品李"},
        {time: "00:08", lyric: "Amin"},
        {time: "00:10", lyric: "李宗盛"},
        {time: "00:12", lyric: "李宗盛"},
        {time: "00:19", lyric: "阴天在不开灯的房间"},
        {time: "00:23", lyric: "当所有思绪都一点一点沉淀"},
        {time: "00:26", lyric: "爱情究竟是精神鸦片"},
        {time: "00:29", lyric: "还是世纪末的无聊消遣"},
        {time: "00:34", lyric: "香烟氲成一摊光圈"},
        {time: "00:37", lyric: "和他的照片就摆在手边"},
        {time: "00:41", lyric: "傻傻两个人笑得多甜"},
        {time: "00:47", lyric: "开始总是分分钟都妙不可言"},
        {time: "00:51", lyric: "谁都认为热情它永不会减"},
        {time: "00:54", lyric: "除了激情褪去后的那一点点倦"},
        {time: "01:01", lyric: "也许像谁说过的贪得无厌"},
        {time: "01:05", lyric: "活该应了谁说过的不知检点"},
        {time: "01:09", lyric: "总之那几年感性赢了理性那一面"},
        {time: "01:31", lyric: "阴天在不开灯的房间"},
        {time: "01:34", lyric: "当所有思绪都一点一点沉淀"},
        {time: "01:38", lyric: "爱恨情欲里的疑点盲点"},
        {time: "01:41", lyric: "呼之欲出那么明显"},
        {time: "01:45", lyric: "女孩通通让到一边"},
        {time: "01:48", lyric: "这歌里的细微末节就算都体验"},
        {time: "01:52", lyric: "若想真明白真要好几年"},
        {time: "02:27", lyric: "回想那一天喧闹的喜宴"},
        {time: "02:35", lyric: "耳边想起的究竟是序曲或完结篇?"},
        {time: "02:42", lyric: "感情不就是你情我愿"},
        {time: "02:45", lyric: "最好爱狠扯平俩不相欠"},
        {time: "02:49", lyric: "感情说穿了一人挣脱的一人去捡"},
        {time: "02:55", lyric: "男人大可不必百口莫辨"},
        {time: "03:00", lyric: "女人实在无须楚楚可怜"},
        {time: "03:03", lyric: "总之那几年你们俩个没有缘"},
        {time: "03:13", lyric: "阴天在不开灯的房间"},
        {time: "03:16", lyric: "当所有思绪都一点一点沉淀"},
        {time: "03:20", lyric: "爱情究竟是精神鸦"},
        {time: "03:23", lyric: "还是世纪末的无聊消遣"},
        {time: "03:27", lyric: "香烟氲成一摊光圈"},
        {time: "03:31", lyric: "和他的照片就摆在手边"},
        {time: "03:34", lyric: "傻傻两个人笑得多甜"},
        {time: "03:41", lyric: "傻傻两个人笑得多甜"}]
    },
    {
        id: "1",
        songs: "幸福的错觉",
        name: "任重",
        src: "music/幸福的错觉.mp3",
        alltime: "04:36",
        photo: "images/rz.jpg",
        lyrics: [{time: "00:00", lyric: " "},
            {time: "00:01", lyric: "幸福的错觉"},
            {time: "00:02", lyric: " "},
            {time: "00:03", lyric: "演唱：任重"},
            {time: "00:04", lyric: "作曲：祁勃力"},
            {time: "00:06", lyric: "作词：樊凡 孙艺 祁勃力"},
            {time: "00:08", lyric: ""},
            {time: "00:18", lyric: "祝福明天"},
            {time: "00:21", lyric: "我不该就这样走远"},
            {time: "00:25", lyric: "假设了千万遍"},
            {time: "00:27", lyric: "又如何能改变"},
            {time: "00:32", lyric: "我们的这些天"},
            {time: "00:35", lyric: "我回想你的脸"},
            {time: "00:37", lyric: "怎么说再见"},
            {time: "00:40", lyric: "画面 冻结在一瞬间"},
            {time: "00:46", lyric: ""},
            {time: "00:47", lyric: "时间 留下了无解的思念"},
            {time: "00:55", lyric: "回忆敌不过"},
            {time: "00:58", lyric: "距离的遥远"},
            {time: "01:01", lyric: "那些往昔"},
            {time: "01:04", lyric: "如童话般美丽的记忆"},
            {time: "01:10", lyric: "如今 却已散落一地"},
            {time: "01:16", lyric: ""},
            {time: "01:16", lyric: "怎样才可以"},
            {time: "01:19", lyric: "说服了我自己"},
            {time: "01:24", lyric: "我们拥有的曾经"},
            {time: "01:28", lyric: "并不算爱情"},
            {time: "01:31", lyric: "为什么忽然间"},
            {time: "01:35", lyric: "我差一点相信"},
            {time: "01:39", lyric: "完美的结局"},
            {time: "01:41", lyric: "属于我和你"},
            {time: "01:45", lyric: ""},
            {time: "01:45", lyric: "怎样才可以"},
            {time: "01:48", lyric: ""},
            {time: "01:54", lyric: "彻底把过去"},
            {time: "01:56", lyric: "在心底抹去"},
            {time: "02:00", lyric: "如果说那幸福"},
            {time: "02:04", lyric: "不过都是错觉"},
            {time: "02:09", lyric: "为何有微笑"},
            {time: "02:11", lyric: "留在照片里"},
            {time: "02:15", lyric: " "},
            {time: "02:16", lyric: " "},
            {time: "02:41", lyric: "时间 留下了无解的思念"},
            {time: "02:49", lyric: "回忆敌不过"},
            {time: "02:51", lyric: "距离的遥远"},
            {time: "02:56", lyric: "那些往昔"},
            {time: "02:58", lyric: "如童话般美丽的记忆"},
            {time: "03:04", lyric: "如今 却已散落一地"},
            {time: "03:10", lyric: " "},
            {time: "03:10", lyric: "怎样才可以"},
            {time: "03:13", lyric: "说服了我自己"},
            {time: "03:19", lyric: "我们拥有的曾经"},
            {time: "03:22", lyric: "并不算爱情"},
            {time: "03:25", lyric: "为什么忽然间"},
            {time: "03:29", lyric: "我差一点相信"},
            {time: "03:34", lyric: "完美的结局"},
            {time: "03:35", lyric: "属于我和你"},
            {time: "03:40", lyric: " "},
            {time: "03:40", lyric: "怎样才可以"},
            {time: "03:43", lyric: "说服了我自己"},
            {time: "03:48", lyric: "彻底把过去"},
            {time: "03:51", lyric: "在心底抹去"},
            {time: "03:55", lyric: "如果说那幸福"},
            {time: "03:59", lyric: "不过都是错觉"},
            {time: "04:03", lyric: "为何有微笑"},
            {time: "04:06", lyric: "留在照片里"}]
    },
    {
        id: "2", songs: "背影", name: "林宥嘉", src: "music/背影.mp3", alltime: "05:54", photo: "images/lyj.jpg", lyrics: [
        {time: "00:02", lyric: "背影"},
        {time: "00:13", lyric: "林宥嘉"},
        {time: "00:30", lyric: ""},
        {time: "00:31", lyric: " "},
        {time: "00:39", lyric: "堵在眼前像一面 玻璃"},
        {time: "00:46", lyric: "挡住了你表情 剩下 只有脚印"},
        {time: "01:02", lyric: "一直向前走 走不完距离"},
        {time: "01:10", lyric: "一直想后退不出回忆"},
        {time: "01:17", lyric: "很高兴有心事 帮我困住自己"},
        {time: "01:28", lyric: ""},
        {time: "01:33", lyric: "你头发上淡淡青草香气"},
        {time: "01:40", lyric: "变成了风才能和我相遇"},
        {time: "01:48", lyric: "你的目光 蒸发成云"},
        {time: "01:56", lyric: "再下成雨我才能够靠近"},
        {time: "02:02", lyric: ""},
        {time: "02:02", lyric: "感谢我不可以 住进你的眼睛"},
        {time: "02:10", lyric: "所以才能 拥抱你的背影"},
        {time: "02:18", lyric: "有再多的遗憾 用来牢牢记住"},
        {time: "02:26", lyric: "不完美 的所有美丽"},
        {time: "02:33", lyric: "感谢我不可以 拥抱你的背影"},
        {time: "02:41", lyric: "所以才能 变成你的背影"},
        {time: "02:49", lyric: "躲在安静角落 不用你回头看"},
        {time: "02:59", lyric: "不用珍惜"},
        {time: "03:05", lyric: ""},
        {time: "03:33", lyric: "我怀里所有温暖的空气"},
        {time: "03:41", lyric: "变成风也不敢和你相遇"},
        {time: "03:48", lyric: "我的心事 蒸发成云"},
        {time: "03:56", lyric: "再下成雨却舍不得淋湿你"},
        {time: "04:02", lyric: ""},
        {time: "04:03", lyric: "感谢我不可以 住进你的眼睛"},
        {time: "04:10", lyric: "所以才能 拥抱你背影"},
        {time: "04:18", lyric: "有再多的遗憾 用来牢牢记住"},
        {time: "04:27", lyric: "不完美 的所有美丽"},
        {time: "04:34", lyric: "感谢我不可以 拥抱你的背影"},
        {time: "04:41", lyric: "所以才能 变成你的背影"},
        {time: "04:49", lyric: "躲在安静角落 不用你回头看"},
        {time: "04:59", lyric: "不用珍惜"},
        {time: "05:04", lyric: ""},
        {time: "05:05", lyric: "感谢我不可以 拥抱你的背影"},
        {time: "05:12", lyric: "所以才能 变成你的背影"},
        {time: "05:20", lyric: "躲在安静角落 如果你回头看"},
        {time: "05:30", lyric: "不用在意"},
        {time: "05:35", lyric: ""},
        {time: "05:41", lyric: "背影"}
    ]
    },
    {
        id: "3",
        songs: "红玫瑰",
        name: "陈奕迅",
        src: "music/红玫瑰.mp3",
        alltime: "04:00",
        photo: "images/cyx.jpg",
        lyrics: [{time: "00:01", lyric: "红玫瑰"},
            {time: "00:04", lyric: "陈奕迅"},
            {time: "00:06", lyric: "《认了吧》"},
            {time: "00:11", lyric: "www.22lrc.com☆x大紫↗ 制作"},
            {time: "00:16", lyric: "梦里梦到醒不来的梦"},
            {time: "00:18", lyric: "红线里被软禁的红"},
            {time: "00:23", lyric: "所有刺激剩下疲乏的痛 再无动于衷"},
            {time: "00:29", lyric: "从背后抱你的时候 期待的却是她的面容"},
            {time: "00:37", lyric: "说来实在嘲讽 我不太懂 偏渴望你懂"},
            {time: "00:44", lyric: "是否幸福轻得太沉重"},
            {time: "00:47", lyric: "过度使用不痒不痛 烂熟透红空洞了的瞳孔"},
            {time: "00:55", lyric: "终于掏空 终于有始无终"},
            {time: "00:59", lyric: "得不到的永远在骚动"},
            {time: "01:03", lyric: "被偏爱的 都有恃无恐"},
            {time: "01:06", lyric: "玫瑰的红 容易受伤的梦"},
            {time: "01:10", lyric: "握在手中却流失于指缝"},
            {time: "01:14", lyric: "又落空"},
            {time: "01:29", lyric: "红是朱砂痣烙印心口"},
            {time: "01:33", lyric: "红是蚊子血般平庸"},
            {time: "01:37", lyric: "时间美化那仅有的悸动　也磨平激动"},
            {time: "01:44", lyric: "从背后抱你的时候 期待的却是她的面容"},
            {time: "01:52", lyric: "说来实在嘲讽 我不太懂 片刻望你懂"},
            {time: "01:59", lyric: "是否幸福轻得太沉重"},
            {time: "02:03", lyric: "过度使用 不痒不痛"},
            {time: "02:06", lyric: "烂熟透红空洞了的瞳孔"},
            {time: "02:11", lyric: "终于掏空 终于有始无终"},
            {time: "02:14", lyric: "得不到的永远在骚动"},
            {time: "02:17", lyric: "被偏爱的都有恃无恐"},
            {time: "02:22", lyric: "玫瑰的红 容易受伤的梦"},
            {time: "02:25", lyric: "握在手中却流失于指缝"},
            {time: "02:29", lyric: "又落空"},
            {time: "02:33", lyric: "www.22lrc.com☆x大紫↗ 制作"},
            {time: "02:44", lyric: "是否说爱都太过沉重"},
            {time: "02:47", lyric: "过度使用不痒不痛"},
            {time: "02:52", lyric: "烧得火红 蛇行缠绕心中"},
            {time: "02:55", lyric: "终于冷冻终于有始无终"},
            {time: "02:59", lyric: "得不到的永远在骚动"},
            {time: "03:02", lyric: "被偏爱的都有恃无恐"},
            {time: "03:06", lyric: "玫瑰的红 容易受伤的梦"},
            {time: "03:11", lyric: "握在手中却流失于指缝"},
            {time: "03:14", lyric: "得不到的永远在骚动"},
            {time: "03:18", lyric: "被偏爱的 都有恃无恐"},
            {time: "03:22", lyric: "玫瑰的红 伤口绽放的梦"},
            {time: "03:25", lyric: "握在手中却流失于指缝"},
            {time: "03:29", lyric: "再落空"}]
    },
    {
        id: "4",
        songs: "初爱",
        name: "杨宗纬",
        src: "music/初爱.mp3",
        alltime: "03:53",
        photo: "images/yzw.jpg",
        lyrics: [{time: "00:01", lyric: "初爱"},
            {time: "00:02", lyric: "作词：黄婷 作曲：木村充利"},
            {time: "00:04", lyric: "演唱：杨宗纬"},
            {time: "00:07", lyric: ""},
            {time: "00:25", lyric: "永远感激 你狂奔过操场 来到我眼前"},
            {time: "00:31", lyric: "阳光灿烂 烫红了你双颊 温暖你笑靥"},
            {time: "00:36", lyric: "那时节 黄澄澄的落叶 铺满整条街"},
            {time: "00:42", lyric: "下课钟声 荡过悠悠岁月"},
            {time: "00:46", lyric: "长大后 世界像一张网 网住我们的翅膀"},
            {time: "00:54", lyric: "回忆 沉甸甸在心上"},
            {time: "00:57", lyric: "偶尔 轻声独唱"},
            {time: "00:59", lyric: "是否能找回消失的力量"},
            {time: "01:03", lyric: "想起了初爱 想起最初的梦已不在"},
            {time: "01:08", lyric: ""},
            {time: "01:09", lyric: "想起青春 曾无畏无惧 无所谓失败"},
            {time: "01:14", lyric: "当时看见彩虹就笑开 一无窒碍在胸怀"},
            {time: "01:20", lyric: "带你抛下课堂 翻过围墙 只为了往一片大海"},
            {time: "01:27", lyric: "告别了初爱 告别了制服上的名牌"},
            {time: "01:32", lyric: "告别天真 学着去拨开 雨天的阴霾"},
            {time: "01:39", lyric: "沮丧失落反复地重来 不能放弃勇敢去爱"},
            {time: "01:44", lyric: "是 你让我 还相信未来"},
            {time: "01:49", lyric: ""},
            {time: "02:04", lyric: "若不是你 包容我年少时 轻狂和执拗"},
            {time: "02:09", lyric: "我不可能 在颠簸的路上 走得那么好"},
            {time: "02:14", lyric: "虽然你 终究没等到我 做你的骄傲"},
            {time: "02:21", lyric: "却永远是 我生命中的美好"},
            {time: "02:28", lyric: "总是会在碰撞中回望 脆弱累积成担当"},
            {time: "02:33", lyric: "总要 一段一段错过"},
            {time: "02:36", lyric: "愈合 那时的伤"},
            {time: "02:39", lyric: ""},
            {time: "02:39", lyric: "你却早已经不在我身旁"},
            {time: "02:42", lyric: "永远的初爱 永远最初的梦最精彩"},
            {time: "02:47", lyric: "想起青春 曾无畏无惧 无所谓失败"},
            {time: "02:54", lyric: "当时看见彩虹就笑开 一无窒碍在胸怀"},
            {time: "03:00", lyric: "带你抛下课堂 翻过围墙 只为了往一片大海"},
            {time: "03:05", lyric: "告别了初爱 告别了制服上的名牌"},
            {time: "03:11", lyric: ""},
            {time: "03:12", lyric: "告别天真 学会去拨开 雨天的阴霾"},
            {time: "03:17", lyric: "沮丧失落反复地重来 不能放弃勇敢去爱"},
            {time: "03:23", lyric: ""},
            {time: "03:24", lyric: "是 你让我 还相信未来"},
            {time: "03:28", lyric: ""},
            {time: "03:31", lyric: "我 想起你 就不会 崩坏"},
            {time: "03:38", lyric: ""}]
    },
    {
        id: "5", songs: "情书", name: "张学友", src: "music/情书.mp3", alltime: "04.06", photo: "images/zxy.jpg", lyrics: [
        {time: "00:01", lyric: "情书"},
        {time: "00:01", lyric: "作词 :姚若龙　作曲 :戚小恋"},
        {time: "00:02", lyric: "演唱：张学友"},
        {time: "00:03", lyric: ""},
        {time: "00:23", lyric: "你瘦了憔悴的让我好心疼"},
        {time: "00:27", lyric: "有时候爱情比时间还残忍"},
        {time: "00:32", lyric: "有人变得盲目"},
        {time: "00:34", lyric: "而奋不顾身"},
        {time: "00:35", lyric: "忘了爱 要两个同样　"},
        {time: "00:38", lyric: "用心的人"},
        {time: "00:41", lyric: "你醉了脆弱得藏不住泪痕"},
        {time: "00:46", lyric: "我知道绝望比冬天还寒冷"},
        {time: "00:50", lyric: "你恨自己是个"},
        {time: "00:52", lyric: "怕孤独的人"},
        {time: "00:54", lyric: "偏偏又爱上自由自私的灵魂"},
        {time: "00:59", lyric: ""},
        {time: "01:03", lyric: "你带着他唯一写过的情书"},
        {time: "01:07", lyric: "想证明当初爱得并不糊涂"},
        {time: "01:11", lyric: "他曾为了你的逃离颓废痛苦"},
        {time: "01:16", lyric: "也为了破镜重圆抱着你哭"},
        {time: "01:22", lyric: "哦 可惜爱不是几滴眼泪几封情书"},
        {time: "01:27", lyric: "哦 这样的话或许有点残酷"},
        {time: "01:32", lyric: ""},
        {time: "01:33", lyric: "等待着别人给幸福的人"},
        {time: "01:36", lyric: "往往过得都不怎么幸福"},
        {time: "01:41", lyric: "哦 可惜爱不是忍着眼泪留着情书"},
        {time: "01:46", lyric: "哦 伤口清醒要比昏迷痛楚"},
        {time: "01:51", lyric: "紧闭着双眼 又拖着错误"},
        {time: "01:55", lyric: "真爱 来临时你又要怎么"},
        {time: "01:59", lyric: "留得住"},
        {time: "02:02", lyric: ""},
        {time: "02:19", lyric: "你醉了脆弱得藏不住泪痕"},
        {time: "02:24", lyric: "我知道绝望比冬天还寒冷"},
        {time: "02:28", lyric: "你恨自己是个"},
        {time: "02:31", lyric: "怕孤独的人"},
        {time: "02:32", lyric: "偏偏又爱上自由自私的灵魂"},
        {time: "02:37", lyric: ""},
        {time: "02:41", lyric: "你带着他唯一写过的情书"},
        {time: "02:45", lyric: "想证明当初爱得并不糊涂"},
        {time: "02:49", lyric: "他曾为了你的逃离颓废痛苦"},
        {time: "02:55", lyric: "也为了破镜重圆抱着你哭"},
        {time: "03:00", lyric: "哦 可惜爱不是几滴眼泪几封情书"},
        {time: "03:05", lyric: "哦 这样的话或许有点残酷"},
        {time: "03:11", lyric: "等待着别人给幸福的人"},
        {time: "03:15", lyric: "往往过得都不怎么幸福"},
        {time: "03:19", lyric: "哦 可惜爱不是忍着眼泪留着情书"},
        {time: "03:24", lyric: "哦 伤口清醒要比昏迷痛楚"},
        {time: "03:30", lyric: "紧闭着双眼 又拖着错误"},
        {time: "03:33", lyric: "真爱 来临时你又要怎么"},
        {time: "03:37", lyric: "留得住"},
        {time: "03:40", lyric: ""}
    ]
    },
    {
        id: "6",
        songs: "追光者(钢琴曲)",
        name: "昼夜",
        src: "music/追光者.mp3",
        alltime: "03:54",
        photo: "../img/chun3.png",
        lyrics: [
            {time: '00:00',lyric:'纯音乐，请欣赏' }
        ]
    },
    {
        id: "7",
        songs: "只要平凡",
        name: "张杰&张碧晨",
        src: "music/只要平凡.mp3",
        alltime: "03:53",
        photo: "../img/zhiyao.png",
        lyrics: [
            {time: "00:00", lyric: "张杰、张碧晨 - 只要平凡"},
            {time: "00:01", lyric: "电影《我不是药神》主题曲"},
            {time: "00:03", lyric: ""},
            {time: "00:04", lyric: "也许很远或是昨天"},
            {time: "00:08", lyric: "在这里或在对岸"},
            {time: "00:12", lyric: "长路辗转离合悲欢"},
            {time: "00:16", lyric: "人聚又人散"},
            {time: "00:20", lyric: "放过对错才知答案"},
            {time: "00:24", lyric: "活着的勇敢"},
            {time: "00:28", lyric: "没有神的光环"},
            {time: "00:32", lyric: "你我生而平凡"},
            {time: "00:37", lyric: "在心碎中认清遗憾"},
            {time: "00:41", lyric: "生命漫长也短暂"},
            {time: "00:45", lyric: "跳动心脏长出藤蔓"},
            {time: "00:49", lyric: "愿为险而战"},
            {time: "00:53", lyric: "跌入灰暗坠入深渊"},
            {time: "00:57", lyric: "沾满泥土的脸"},
            {time: "01:01", lyric: "没有神的光环"},
            {time: "01:05", lyric: "握紧手中的平凡"},
            {time: "01:10", lyric: "此心此生无憾"},
            {time: "01:14", lyric: "生命的火已点燃"},
            {time: "01:17", lyric: ""},
            {time: "01:20", lyric: "有一天也许会走远"},
            {time: "01:24", lyric: "也许还能再相见"},
            {time: "01:29", lyric: "无论在人群在天边"},
            {time: "01:32", lyric: "让我再看清你的脸"},
            {time: "01:37", lyric: "任泪水铺满了双眼"},
            {time: "01:41", lyric: "虽无言泪满面"},
            {time: "01:45", lyric: "不要神的光环"},
            {time: "01:49", lyric: "只要你的平凡"},
            {time: "02:36", lyric: ""},
            {time: "02:39", lyric: "在心碎中认清遗憾"},
            {time: "02:43", lyric: "生命漫长也短暂"},
            {time: "02:47", lyric: "跳动心脏长出藤蔓"},
            {time: "02:51", lyric: "愿为险而战"},
            {time: "02:55", lyric: "跌入灰暗坠入深渊"},
            {time: "02:59", lyric: "沾满泥土的脸"},
            {time: "03:04", lyric: "没有神的光环"},
            {time: "03:07", lyric: "握紧手中的平凡"},
            {time: "03:12", lyric: "有一天也许会走远"},
            {time: "03:16", lyric: "也许还能再相见"},
            {time: "03:20", lyric: "无论在人群在天边"},
            {time: "03:24", lyric: "让我再看清你的脸"},
            {time: "03:28", lyric: "任泪水铺满了双眼"},
            {time: "03:32", lyric: "虽无言泪满面"},
            {time: "03:37", lyric: "不要神的光环"},
            {time: "03:40", lyric: "只要你的平凡"},
            {time: "03:45", lyric: "此心此生无憾"},
            {time: "03:49", lyric: "生命的火已点燃"},
            {time: "03:53", lyric: ""}, 
        ]
    },
    {
        id: "8",
        songs: "梦中的婚礼(钢琴曲)",
        name: "Richard Clayderman",
        src: "music/梦中的婚礼.mp3",
        alltime: "02:42",
        photo: "../img/chun1.png",
        lyrics: [
            {time: '00:00',lyric:'纯音乐，请欣赏' }
        ]
    },
    {
        id: "9",
        songs: "菊次郎的夏天",
        name: "K_Williams",
        src: "music/菊次郎的夏天.mp3",
        alltime: "03:20",
        photo: "../img/chun2.png",
        lyrics: [
            {time: '00:00',lyric:'纯音乐，请欣赏' }
        ]
    },
    {
        id: "10",
        songs: "遇见",
        name: "徐晶晶",
        src: "music/遇见.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "这么多年没有见面"},
            {time: "00:20", lyric: "你的身边多了一张陌生的脸"},
            {time: "00:27", lyric: "如今我已没了感觉"},
            {time: "00:33", lyric: "就像一个没了联系的同学"},
            {time: "00:40", lyric: "怎么说也爱过几年"},
            {time: "00:46", lyric: "那段青春有你陪伴多甜"},
            {time: "00:53", lyric: "祝福你找到属于你的缘"},
            {time: "01:19", lyric: "这么多年没有见面"},
            {time: "01:26", lyric: "你的身边多了一张陌生的脸"},
            {time: "01:33", lyric: "如今我已没了感觉"},
            {time: "01:39", lyric: "就像一个没了联系的同学"},
            {time: "01:45", lyric: "怎么说也爱过几年"},
            {time: "01:51", lyric: "那段青春有你陪伴多甜"},
            {time: "01:57", lyric: "祝福你找到属于你的缘"},
          
        ]
    },
    {
        id: "11",
        songs: "原味",
        name: "徐晶晶",
        src: "music/原味.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "爱的原味 冲成咖啡"},
            {time: "00:20", lyric: "各种口味 倒进酒杯"},
            {time: "00:27", lyric: "你拿起它 摔个粉碎"},
            {time: "00:33", lyric: "就像我们的感情"},
            {time: "00:40", lyric: "本来以为 爱情多美"},
            {time: "00:46", lyric: "就像黑咖啡的原味"},
            {time: "00:53", lyric: "祝苦涩的香 甜的回味"},
            {time: "01:19", lyric: "缠绕心中永不悔"},
            {time: "01:26", lyric: "爱的原味 冲成咖啡"},
            {time: "01:33", lyric: "各种口味 倒进酒杯"},
            {time: "01:39", lyric: "你拿起它 摔个粉碎"},
            {time: "01:45", lyric: "就像我们的感情"},
            {time: "01:51", lyric: "本来以为 爱情多美"},
            {time: "01:57", lyric: "就像黑咖啡的原味"},
          
        ]
    },
    {
        id: "12",
        songs: "远方",
        name: "徐晶晶",
        src: "music/远方.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "远方的爱人 我爱你多深"},
            {time: "00:20", lyric: "可是却被距离阻隔"},
            {time: "00:27", lyric: "无法交换体温"},
            {time: "00:33", lyric: "你是否还在等"},
            {time: "00:40", lyric: "通讯工具再多 也难敌"},
            {time: "00:46", lyric: "面对面的一个吻"},
            {time: "00:53", lyric: "我亲爱的爱人虽然你在远方"},
            {time: "01:19", lyric: "可是我的想念还和当初一样"},
            {time: "01:26", lyric: "这样的等待还要多久"},
            {time: "01:33", lyric: "远方的爱人 我爱你多深"},
            {time: "01:45", lyric: "可是却被距离阻隔"},
            {time: "01:52", lyric: "无法交换体温"},
            {time: "02:04", lyric: "你是否还在等"},
            {time: "02:10", lyric: "通讯工具再多 也难敌"},
            {time: "02:17", lyric: "面对面的一个吻"},
            {time: "02:22", lyric: "我亲爱的爱人虽然你在远方"},
            {time: "02:30", lyric: "可是我的想念还和当初一样"},
            {time: "02:36", lyric: "这样的等待还要多久"}
        ]
    },
    {
        id: "13",
        songs: "再也不见",
        name: "徐晶晶",
        src: "music/再也不见.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "夜深人静的时候"},
            {time: "00:20", lyric: "有人拉住我的手"},
            {time: "00:27", lyric: "是我们的回忆仍在"},
            {time: "00:33", lyric: "一分一秒不眠不休"},
            {time: "00:40", lyric: "转眼天已经亮了"},
            {time: "00:46", lyric: "你梦里那个人呢"},
            {time: "00:53", lyric: "他曾躺在你身边"},
            {time: "01:19", lyric: "唤醒你每个白天"},
            {time: "01:26", lyric: "夜深人静的时候"},
            {time: "01:33", lyric: "有人拉住我的手"},
            {time: "01:45", lyric: "是我们的回忆仍在"},
            {time: "01:52", lyric: "一分一秒不眠不休"},
            {time: "02:04", lyric: "转眼天已经亮了"},
            {time: "02:10", lyric: "你梦里那个人呢"},
            {time: "02:17", lyric: "他曾躺在你身边"},
            {time: "02:22", lyric: "唤醒你每个白天"},
        ]
    },
    {
        id: "14",
        songs: "再也没有",
        name: "徐晶晶",
        src: "music/再也没有.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "再也没有这样的心情"},
            {time: "00:20", lyric: "再也不见这样的年龄"},
            {time: "00:27", lyric: "时光飞逝让人难解释"},
            {time: "00:33", lyric: "尤其当我又想起你时"},
            {time: "00:40", lyric: "说多了自己会伤心"},
            {time: "00:46", lyric: "那么久依然难忘记"},
            {time: "00:53", lyric: "再也没有这样的心情"},
            {time: "01:19", lyric: "再也不见这样的年龄"},
            {time: "01:26", lyric: "时光飞逝让人难解释"},
            {time: "01:33", lyric: "尤其当我又想起你时"},
            {time: "01:45", lyric: "说多了自己会伤心"},
            {time: "01:52", lyric: "那么久依然难忘记"},
           
        ]
    },
    {
        id: "15",
        songs: "在一起",
        name: "徐晶晶",
        src: "music/在一起.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "这世上最动听 是你说在一起"},
            {time: "00:20", lyric: "只要你一句 我什么都愿意"},
            {time: "00:27", lyric: "时光飞逝让人难解释"},
            {time: "00:33", lyric: "这世上最动听 是你说在一起"},
            {time: "00:40", lyric: "只要你一句 我什么都愿意"},
            {time: "00:46", lyric: "时光飞逝让人难解释"},
           
        ]
    },
    {
        id: "16",
        songs: "造化",
        name: "徐晶晶",
        src: "music/造化.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "你是水中月 我是镜中花"},
            {time: "00:20", lyric: "远远地相望 远远的牵挂"},
            {time: "00:27", lyric: "这样看着你 却无法靠近"},
            {time: "00:33", lyric: "这是不是上天安排的造化"},
            {time: "00:40", lyric: "你在那边对我弹琵琶"},
            {time: "00:46", lyric: "时琴声悠扬却那么遥远"},
            {time: "00:53", lyric: "无法触碰的情感"},
            {time: "01:19", lyric: "就好像远方的牵挂"},
            {time: "01:26", lyric: "你是水中月 我是镜中花"},
            {time: "01:33", lyric: "远远地相望 远远的牵挂"},
            {time: "01:45", lyric: "这样看着你 却无法靠近"},
            {time: "01:52", lyric: "这是不是上天安排的造化"},
            {time: "02:04", lyric: "你在那边对我弹琵琶"},
            {time: "02:10", lyric: "琴声悠扬却那么遥远"},
            {time: "02:17", lyric: "无法触碰的情感"},
            {time: "02:22", lyric: " 就好像远方的牵挂 "},
        ]
    },
    {
        id: "17",
        songs: "怎么活",
        name: "徐晶晶",
        src: "music/怎么活.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "我们的幸福"},
            {time: "00:20", lyric: "化成了音符"},
            {time: "00:27", lyric: "你歌唱的声音"},
            {time: "00:33", lyric: "融化我的温度"},
            {time: "00:40", lyric: "欢乐那么多"},
            {time: "00:46", lyric: "开心那么疯"},
            {time: "00:53", lyric: "如果有天你不属于我"},
            {time: "01:19", lyric: "我该怎么活"},
            {time: "01:26", lyric: "我该怎么过"},
            {time: "01:33", lyric: "我们的幸福"},
            {time: "01:45", lyric: "化成了音符"},
            {time: "01:52", lyric: "我们的幸福"},
            {time: "02:04", lyric: "化成了音符"},
            {time: "02:10", lyric: "你歌唱的声音"},
            {time: "02:17", lyric: "融化我的温度"},
            {time: "02:22", lyric: " 欢乐那么多 "},
            {time: "02:45", lyric: "开心那么疯"},
            {time: "02:52", lyric: "如果有天你不属于我"},
            {time: "03:04", lyric: "我该怎么活"},
            {time: "03:10", lyric: "我该怎么过"},
            {time: "03:17", lyric: "我们的幸福"},
            {time: "03:22", lyric: " 化成了音符 "},
        ]
    },
    {
        id: "18",
        songs: "占有欲",
        name: "徐晶晶",
        src: "music/占有欲.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "这样就已经够了"},
            {time: "00:20", lyric: "还怎样才满足呢"},
            {time: "00:27", lyric: "我已经没剩什么"},
            {time: "00:33", lyric: "不如你全都带走吧"},
            {time: "00:40", lyric: "太贪心 是失败的原因"},
            {time: "00:46", lyric: "想占有 对方所有的东西"},
            {time: "00:53", lyric: "包括我 也有一样的问题"},
            {time: "01:19", lyric: "只是占有欲毕竟不是爱情"},
            {time: "01:26", lyric: "太贪心 是失败的原因"},
            {time: "01:33", lyric: "想占有 对方所有的事情"},
            {time: "01:45", lyric: "包括我 也有一样的问题"},
            {time: "01:52", lyric: "只是占有欲毕竟不是爱情"},
            {time: "02:04", lyric: "太贪心 是失败的原因"},
            {time: "02:10", lyric: "这样就已经够了"},
            {time: "02:17", lyric: "还怎样才满足呢"},
            {time: "02:22", lyric: " 我已经没剩什么 "},
            {time: "02:45", lyric: "不如你全都带走吧"},
            {time: "05:52", lyric: "太贪心 是失败的原因"},
            {time: "03:04", lyric: "想占有 对方所有的东西"},
            {time: "03:10", lyric: "包括我 也有一样的问题"},
            {time: "03:17", lyric: "只是占有欲毕竟不是爱情"},
            {time: "03:22", lyric: " 太贪心 是失败的原因 "},
            {time: "03:25", lyric: "想占有 对方所有的事情"},
            {time: "03:31", lyric: " 包括我 也有一样的问题 "},
        ]
    },
    {
        id: "19",
        songs: "折磨",
        name: "徐晶晶",
        src: "music/折磨.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "爱上你是一个错"},
            {time: "00:20", lyric: "明知道根本没结果呢"},
            {time: "00:27", lyric: "一开是就如此冷漠"},
            {time: "00:33", lyric: "我却依然苦苦追求"},
            {time: "00:40", lyric: "你说这都是你自找的"},
            {time: "00:46", lyric: "我又没让你受着折磨"},
            {time: "00:53", lyric: "可是我只想让你快乐"},
            {time: "01:19", lyric: "没想到最后自我折磨"},
            {time: "01:26", lyric: "爱上你是一个错"},
            {time: "01:33", lyric: "明知道根本没结果"},
            {time: "01:45", lyric: "一开是就如此冷漠"},
            {time: "01:52", lyric: "我却依然苦苦追求"},
            {time: "02:04", lyric: "你说这都是你自找的"},
            {time: "02:10", lyric: "我又没让你受着折磨"},
            {time: "02:17", lyric: "可是我只想让你快乐"},
            {time: "02:22", lyric: "没想到最后自我折磨"},
            
        ]
    },
    {
        id: "20",
        songs: "爱她的香水",
        name: "许婉琳",
        src: "music/爱她的香水.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "看不清的身影总是耍单飞"},
            {time: "00:20", lyric: "寻不到追求的香味"},
            {time: "00:27", lyric: "天长地久的爱不会太昂贵"},
            {time: "00:33", lyric: "其实也可以来一回"},
            {time: "00:40", lyric: "一睹美丽的容颜"},
            {time: "00:46", lyric: "你的美让人昏迷的药水"},
            {time: "00:53", lyric: "百转千回的依偎"},
            {time: "01:19", lyric: "就像是空气之中炫耀的美"},
            {time: "01:26", lyric: "啦爱她的香味"},
            {time: "01:33", lyric: "全部都体会"},
            {time: "01:45", lyric: "啦愉快的原味"},
            {time: "01:52", lyric: "这属于我的珍贵"},
            {time: "02:04", lyric: "不一样的所为"},
            {time: "02:10", lyric: "像你飞像你追"},
            {time: "02:17", lyric: "亲爱的不要退回"},
            {time: "02:22", lyric: "不要再像谁麻醉"},
            {time: "02:45", lyric: "看不清的身影总是耍单飞"},
            {time: "05:52", lyric: "寻不到追求的香味"},
            {time: "03:04", lyric: "天长地久的爱不会太昂贵"},
            {time: "03:10", lyric: "其实也可以来一回"},
            {time: "03:17", lyric: "一睹美丽的容颜"},
            {time: "03:22", lyric: "你的美让人昏迷的药水"},
            {time: "03:25", lyric: "百转千回的依偎"},
            {time: "03:31", lyric: "就像是空气之中炫耀的美"},
            {time: "03:37", lyric: "啦爱她的香味"},
            {time: "03:42", lyric: "全部都体会"},
            {time: "03:45", lyric: "不一样的所为"},
            {time: "03:52", lyric: "像你飞像你追"},
            {time: "03:57", lyric: "亲爱的不要退回"},
            {time: "04:02", lyric: "不要再像谁麻醉"},
            {time: "04:08", lyric: "看不清的身影总是耍单飞"},
            {time: "04:15", lyric: "寻不到追求的香味"},
            {time: "04:22", lyric: "天长地久的爱不会太昂贵"},
            {time: "04:28", lyric: "其实也可以来一回"},
            {time: "04:35", lyric: "一睹美丽的容颜"},
            {time: "04:42", lyric: "你的美让人昏迷的药水"},
            {time: "04:48", lyric: "百转千回的依偎"},
            {time: "04:53", lyric: "就像是空气之中炫耀的美"},
            {time: "05:00", lyric: "啦爱她的香味"},
            {time: "05:03", lyric: "全部都体会"}
            
        ]
    },
    {
        id: "21",
        songs: "比什么都重要",
        name: "许婉琳",
        src: "music/比什么都重要.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "思念你让我自己有了方向"},
            {time: "00:20", lyric: "思念你让我日子不再无聊"},
            {time: "00:27", lyric: "你的音容笑貌丰富我生活"},
            {time: "00:33", lyric: "想和你一起是不是好奢侈"},
            {time: "00:40", lyric: "未来是个什么样我已不清楚"},
            {time: "00:46", lyric: "你的魅力让我停下了脚步"},
            {time: "00:53", lyric: "你的笑容融化心上的冰"},
            {time: "01:19", lyric: "你的身影是我喜欢的树"},
            {time: "01:26", lyric: "我不知道自己应不应该"},
            {time: "01:33", lyric: "依然的相信你"},
            {time: "01:45", lyric: "你能不能给我平平淡淡"},
            {time: "01:52", lyric: "我想要的幸福"},
            {time: "02:04", lyric: "喜欢你"},
            {time: "02:10", lyric: "啦啦啦啦啦啦"},
            {time: "02:17", lyric: "世界千变万化"},
            {time: "02:22", lyric: "怕到哪一天以后"},
            {time: "02:45", lyric: "不认识我啊"},
            {time: "05:52", lyric: "喜欢你"},
            {time: "03:04", lyric: "啦啦啦啦啦啦"},
            {time: "03:10", lyric: "如果你不知道"},
            {time: "03:17", lyric: "你的一切比什么都重要"},
            {time: "03:22", lyric: "思念你让我自己有了方向"},
            {time: "03:25", lyric: "思念你让我日子不再无聊"},
            {time: "03:31", lyric: "你的音容笑貌丰富我生活"},
            {time: "03:37", lyric: "未来是个什么样我已不清楚"},
            {time: "03:42", lyric: "你的魅力让我停下了脚步"},
            {time: "03:45", lyric: "你的笑容融化心上的冰"},
            {time: "03:52", lyric: "你的身影是我喜欢的树"},
            {time: "03:57", lyric: "我不知道自己应不应该"},
            {time: "04:02", lyric: "依然的相信你"},
            {time: "04:08", lyric: "你能不能给我平平淡淡"},
            {time: "04:15", lyric: "我想要的幸福"},
            {time: "04:22", lyric: "喜欢你"},
            {time: "04:28", lyric: "啦啦啦啦啦啦"},
            {time: "04:35", lyric: "世界千变万化"},
            {time: "04:42", lyric: "怕到哪一天以后"},
            {time: "04:48", lyric: "不认识我啊"},
            {time: "04:53", lyric: "喜欢你"},
            {time: "05:00", lyric: "如果你不知道"},
            {time: "05:03", lyric: "你的一切比什么都重要"}
            
        ]
    },
    {
        id: "22",
        songs: "别孤独",
        name: "许婉琳",
        src: "music/别孤独.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "看着窗外好大的迷雾"},
            {time: "00:20", lyric: "世界变的不再清楚"},
            {time: "00:27", lyric: "茫茫人生有千万条路"},
            {time: "00:33", lyric: "哪个方向才会幸福"},
            {time: "00:40", lyric: "说好不哭"},
            {time: "00:46", lyric: "不要认输"},
            {time: "00:53", lyric: "再多的苦"},
            {time: "01:19", lyric: "不要在乎"},
            {time: "01:26", lyric: "就快要结束"},
            {time: "01:33", lyric: "我们别孤独"},
            {time: "01:45", lyric: "各自走向不归路"},
            {time: "01:52", lyric: "就快要结束"},
            {time: "02:04", lyric: "一定要幸福"},
            {time: "02:10", lyric: "我用笑容祝福"},
            {time: "02:17", lyric: "双眼已模糊"},
            {time: "02:22", lyric: "看着窗外好大的迷雾"},
            {time: "02:45", lyric: "世界变的不再清楚"},
            {time: "05:52", lyric: "茫茫人生有千万条路"},
            {time: "03:04", lyric: "哪个方向才会幸福"},
            {time: "03:10", lyric: "说好不哭"},
            {time: "03:17", lyric: "不要认输"},
            {time: "03:22", lyric: "再多的苦"},
            {time: "03:25", lyric: "不要在乎"},
            {time: "03:31", lyric: "就快要结束"},
            {time: "03:37", lyric: "我们别孤独"},
            {time: "03:42", lyric: "各自走向不归路"},
            {time: "03:45", lyric: "就快要结束"},
            {time: "03:52", lyric: "一定要幸福"},
            {time: "03:57", lyric: "我用笑容祝福"},
            {time: "04:02", lyric: "双眼已模糊"}
            
        ]
    },
    {
        id: "23",
        songs: "不想害怕的我",
        name: "许婉琳",
        src: "music/不想害怕的我.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "你和她有怎样的对白"},
            {time: "00:20", lyric: "会不会像我们一样爱"},
            {time: "00:27", lyric: "真真假假的心摇摆"},
            {time: "00:33", lyric: "最后一刻是谁的舞台"},
            {time: "00:40", lyric: "不开心会怎样说明"},
            {time: "00:46", lyric: "会担心怎样反应"},
            {time: "00:53", lyric: "谁的错不用一刻澄清"},
            {time: "01:19", lyric: "只怪太痴迷"},
            {time: "01:26", lyric: "不想害怕的我"},
            {time: "01:33", lyric: "不需要承诺"},
            {time: "01:45", lyric: "回不去的以后"},
            {time: "01:52", lyric: "剩下的什么"},
            {time: "02:04", lyric: "不想害怕的我"},
            {time: "02:10", lyric: "不能要承诺"},
            {time: "02:17", lyric: "不小心会想多"},
            {time: "02:22", lyric: "爱会不再经过"},
            {time: "02:45", lyric: "你和她有怎样的对白"},
            {time: "05:52", lyric: "会不会像我们一样爱"},
            {time: "03:04", lyric: "真真假假的心摇摆"},
            {time: "03:10", lyric: "最后一刻是谁的舞台"},
            {time: "03:17", lyric: "不开心会怎样说明"},
            {time: "03:22", lyric: "会担心怎样反应"},
            {time: "03:25", lyric: "谁的错不用一刻澄清"},
            {time: "03:31", lyric: "只怪太痴迷"},
            {time: "03:37", lyric: "不想害怕的我"},
            {time: "03:42", lyric: "不需要承诺"},
            {time: "03:45", lyric: "回不去的以后"},
            {time: "03:52", lyric: "剩下的什么"},
            {time: "03:57", lyric: "不想害怕的我"},
            {time: "04:02", lyric: "不能要承诺"},
            {time: "04:08", lyric: "不小心会想多"},
            {time: "04:15", lyric: "爱会不再"},
            {time: "04:22", lyric: "不想害怕的我"},
            {time: "04:28", lyric: "不能要承诺"},
            {time: "04:35", lyric: "不小心会想多"},
            {time: "04:42", lyric: "爱会不再经过"}
          
            
        ]
    },
    {
        id: "24",
        songs: "不小心的误会",
        name: "许婉琳",
        src: "music/不小心的误会.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "天浓浓的又伤悲"},
            {time: "00:20", lyric: "不再是谁对谁飞"},
            {time: "00:27", lyric: "看不见你的憔悴"},
            {time: "00:33", lyric: "等待属于哪一个分轨"},
            {time: "00:40", lyric: "月亮又开始下坠"},
            {time: "00:46", lyric: "奇怪这一次谁又相随"},
            {time: "00:53", lyric: "你来来回回谁对谁非"},
            {time: "01:19", lyric: "犹豫不决怎么面对"},
            {time: "01:26", lyric: "原来你也懂伤悲"},
            {time: "01:33", lyric: "也懂得难过时的滋味"},
            {time: "01:45", lyric: "快乐就算全部都交回"},
            {time: "01:52", lyric: "我还剩下单身的美"},
            {time: "02:04", lyric: "不一定都要无畏"},
            {time: "02:10", lyric: "就算小幸福我也体会"},
            {time: "02:17", lyric: "你不会明白为何爱情会碎"},
            {time: "02:22", lyric: "就当作不小心的误会"},
            {time: "02:45", lyric: "天浓浓的又伤悲"},
            {time: "05:52", lyric: "不再是谁对谁飞"},
            {time: "03:04", lyric: "看不见你的憔悴"},
            {time: "03:10", lyric: "等待属于哪一个分轨"},
            {time: "03:17", lyric: "月亮又开始下坠"},
            {time: "03:22", lyric: "奇怪这一次谁又相随"},
            {time: "03:25", lyric: "你来来回回谁对谁非"},
            {time: "03:31", lyric: "犹豫不决怎么面对"},
            {time: "03:37", lyric: "原来你也懂伤悲"},
            {time: "03:42", lyric: "也懂得难过时的滋味"},
            {time: "03:45", lyric: "快乐就算全部都交回"},
            {time: "03:52", lyric: "我还剩下单身的美"},
            {time: "03:57", lyric: "不一定都要无畏"},
            {time: "04:02", lyric: "就算小幸福我也体会"},
            {time: "04:08", lyric: "你不会明白为何爱情会碎"},
            {time: "04:15", lyric: "就当作不小心的误会"},
            {time: "04:22", lyric: "原来你也懂伤悲"},
            {time: "04:28", lyric: "也懂得难过时的滋味"},
            {time: "04:35", lyric: "快乐就算全部都交回"},
            {time: "04:42", lyric: "我还剩下单身的美"},
            {time: "04:48", lyric: "不一定都要无畏"},
            {time: "04:53", lyric: "就算小幸福我也体会"},
            {time: "05:00", lyric: "你不会明白为何爱情会碎"},
            {time: "05:03", lyric: "就当作不小心的误会"}
            
        ]
    }
    ,
    {
        id: "25",
        songs: "放映的场景",
        name: "许婉琳",
        src: "music/放映的场景.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "爱有点痛会落空"},
            {time: "00:20", lyric: "请不要叫醒的梦"},
            {time: "00:27", lyric: "当没有人再期望"},
            {time: "00:33", lyric: "我也会彷徨"},
            {time: "00:40", lyric: "有颗真心的向往"},
            {time: "00:46", lyric: "到哪一天才会亮"},
            {time: "00:53", lyric: "爱又悠闲又会忙"},
            {time: "01:19", lyric: "请不要太感伤"},
            {time: "01:26", lyric: "王子归来时候刚好"},
            {time: "01:33", lyric: "一定要找到"},
            {time: "01:45", lyric: "就会在下一秒"},
            {time: "01:52", lyric: "统统做记号"},
            {time: "02:04", lyric: "心发出的信号"},
            {time: "02:10", lyric: "互换情报的重要"},
            {time: "02:17", lyric: "开始心荡神摇"},
            {time: "02:22", lyric: "别倒头睡着"},
            {time: "02:45", lyric: "你的美我全部都知道"},
            {time: "05:52", lyric: "像微笑痛苦的烦恼"},
            {time: "03:04", lyric: "昨日的情缘不能再了"},
            {time: "03:10", lyric: "回首舍不得"},
            {time: "03:17", lyric: "需要的好"},
            {time: "03:22", lyric: "爱有点痛会落空"},
            {time: "03:25", lyric: "请不要叫醒的梦"},
            {time: "03:31", lyric: "当没有人再期望"},
            {time: "03:37", lyric: "我也会彷徨"},
            {time: "03:42", lyric: "有颗真心的向往"},
            {time: "03:45", lyric: "到哪一天才会亮"},
            {time: "03:52", lyric: "爱又悠闲又会忙"},
            {time: "03:57", lyric: "请不要太感伤"},
            {time: "04:02", lyric: "王子归来时候刚好"},
            {time: "04:08", lyric: "一定要找到"},
            {time: "04:15", lyric: "就会在下一秒"},
            {time: "04:22", lyric: "统统做记号"},
            {time: "04:28", lyric: "心发出的信号"},
            {time: "04:35", lyric: "互换情报的重要"},
            {time: "04:42", lyric: "开始心荡神摇"},
            {time: "04:48", lyric: "别倒头睡着"},
            {time: "04:53", lyric: "你的美我全部都知道"},
            {time: "05:00", lyric: "像微笑痛苦的烦恼"},
            {time: "05:03", lyric: "昨日的情缘不能再了"},
            {time: "05:09", lyric: "回首舍不得"},
            {time: "05:14", lyric: "需要的好"},
            {time: "05:19", lyric: "你的美我全部都知道"},
            {time: "05:25", lyric: "像微笑痛苦的烦恼"},
            {time: "05:30", lyric: "回首舍不得"}
            
        ]
    },
    {
        id: "26",
        songs: "依然纯真",
        name: "许婉琳",
        src: "music/依然纯真.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "年少时总梦想走天涯"},
            {time: "00:20", lyric: "要把这世界都踩在脚下"},
            {time: "00:27", lyric: "那时候总希望"},
            {time: "00:33", lyric: "不要再长大"},
            {time: "00:40", lyric: "我忍受了风吹和雨打"},
            {time: "00:46", lyric: "可你已经不知到哪去啦"},
            {time: "00:53", lyric: "曾经啊渴望啊美丽的梦啊"},
            {time: "01:19", lyric: "总是在夜里流下两行泪滴"},
            {time: "01:26", lyric: "难道这就是所谓回忆"},
            {time: "01:33", lyric: "不要问我不懂的问题"},
            {time: "01:45", lyric: "让我一个人继续下去"},
            {time: "01:52", lyric: "我是向远方流浪的人"},
            {time: "02:04", lyric: "在寻找一个叫家的门"},
            {time: "02:10", lyric: "尽管还会漫长路程"},
            {time: "02:17", lyric: "脸上的微笑依然纯真"},
            {time: "02:22", lyric: "年少时总梦想走天涯"},
            {time: "02:45", lyric: "要把这世界都踩在脚下"},
            {time: "05:52", lyric: "那时候总希望"},
            {time: "03:04", lyric: "不要再长大"},
            {time: "03:10", lyric: "我忍受了风吹和雨打"},
            {time: "03:17", lyric: "可你已经不知到哪去啦"},
            {time: "03:22", lyric: "曾经啊渴望啊美丽的梦啊"},
            {time: "03:25", lyric: "总是在夜里流下两行泪滴"},
            {time: "03:31", lyric: "难道这就是所谓回忆"},
            {time: "03:37", lyric: "不要问我不懂的问题"},
            {time: "03:42", lyric: "让我一个人继续下去"},
            {time: "03:45", lyric: "我是向远方流浪的人"},
            {time: "03:52", lyric: "在寻找一个叫家的门"},
            {time: "03:57", lyric: "尽管还会漫长路程"},
            {time: "04:02", lyric: "脸上的微笑依然纯真"},
            {time: "04:08", lyric: "我是向远方流浪的人"},
            {time: "04:15", lyric: "在寻找一个叫家的门"},
            {time: "04:22", lyric: "尽管还会漫长路程"},
            {time: "04:28", lyric: "脸上的微笑依然纯真"}
          
            
        ]
    },
    {
        id: "27",
        songs: "再爱我",
        name: "许婉琳",
        src: "music/再爱我.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "月儿像思念翩翩飞"},
            {time: "00:20", lyric: "这回忆把你我牵一对"},
            {time: "00:27", lyric: "美丽就这样在翻回"},
            {time: "00:33", lyric: "我的心情你可能猜不对"},
            {time: "00:40", lyric: "风轻轻摆动 懒懒地吹"},
            {time: "00:46", lyric: "你和我就这样相依偎"},
            {time: "00:53", lyric: "那时候天空那么的美"},
            {time: "01:19", lyric: "好想一切就这样没有累"},
            {time: "01:26", lyric: "结局是谁"},
            {time: "01:33", lyric: "我好疲惫"},
            {time: "01:45", lyric: "辛苦的回味"},
            {time: "01:52", lyric: "你在看谁"},
            {time: "02:04", lyric: "抱紧我啊"},
            {time: "02:10", lyric: "你快回答"},
            {time: "02:17", lyric: "听见我害怕"},
            {time: "02:22", lyric: "再爱我吧"},
            {time: "02:45", lyric: "月儿像思念翩翩飞"},
            {time: "05:52", lyric: "这回忆把你我牵一对"},
            {time: "03:04", lyric: "美丽就这样在翻回"},
            {time: "03:10", lyric: "我忍受了风我的心情你可能猜不对吹"},
            {time: "03:17", lyric: "风轻轻摆动 懒懒地吹"},
            {time: "03:22", lyric: "你和我就这样相依偎"},
            {time: "03:25", lyric: "那时候天空那么的美"},
            {time: "03:31", lyric: "好想一切就这样没有累"},
            {time: "03:37", lyric: "结局是谁"},
            {time: "03:42", lyric: "我好疲惫"},
            {time: "03:45", lyric: "辛苦的回味"},
            {time: "03:52", lyric: "你在看谁"},
            {time: "03:57", lyric: "抱紧我啊"},
            {time: "04:02", lyric: "你快回答"},
            {time: "04:08", lyric: "听见我害怕"},
            {time: "04:15", lyric: "再爱我吧"},
           
            
        ]
    },
    {
        id: "27",
        songs: "真的好难过",
        name: "许婉琳",
        src: "music/真的好难过.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "那个雨后你走以后"},
            {time: "00:20", lyric: "留下冰冷的双眸"},
            {time: "00:27", lyric: "曾经你带给我的感动"},
            {time: "00:33", lyric: "现在还懂不懂"},
            {time: "00:40", lyric: "为什么还会心痛"},
            {time: "00:46", lyric: "还会傻傻等候"},
            {time: "00:53", lyric: "无所谓这个要求"},
            {time: "01:19", lyric: "夜空像是我的梦"},
            {time: "01:26", lyric: "回忆就像无药可救的伤口"},
            {time: "01:33", lyric: "想要说的只是你我的感动"},
            {time: "01:45", lyric: "这种不该孤独难过的时候"},
            {time: "01:52", lyric: "要怎样才能好好的生活"},
            {time: "02:04", lyric: "善良的人是不是都会错过"},
            {time: "02:10", lyric: "所有快乐幸福全部都所有"},
            {time: "02:17", lyric: "拜托不要再追问我"},
            {time: "02:22", lyric: "我真的好难过"},
            {time: "02:45", lyric: "那个雨后你走以后"},
            {time: "05:52", lyric: "留下冰冷的双眸"},
            {time: "03:04", lyric: "曾经你带给我的感动"},
            {time: "03:10", lyric: "现在还懂不懂"},
            {time: "03:17", lyric: "为什么还会心痛"},
            {time: "03:22", lyric: "还会傻傻等候"},
            {time: "03:25", lyric: "无所谓这个要求"},
            {time: "03:31", lyric: "夜空像是我的梦"},
            {time: "03:37", lyric: "回忆就像无药可救的伤口"},
            {time: "03:42", lyric: "想要说的只是你我的感动"},
            {time: "03:45", lyric: "这种不该孤独难过的时候"},
            {time: "03:52", lyric: "要怎样才能好好的生活"},
            {time: "03:57", lyric: "善良的人是不是都会错过"},
            {time: "04:02", lyric: "所有快乐幸福全部都所有"},
            {time: "04:08", lyric: "拜托不要再追问我"},
            {time: "04:15", lyric: "我真的好难过"},
           
            
        ]
    },
    {
        id: "28",
        songs: "只想快乐",
        name: "许婉琳",
        src: "music/只想快乐.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "一切让我们奇迹相遇"},
            {time: "00:20", lyric: "这就注定了我们的缘分"},
            {time: "00:27", lyric: "所有的秘密都是情意"},
            {time: "00:33", lyric: "就不能荒谬的忘记"},
            {time: "00:40", lyric: "一切安排了我再见到你"},
            {time: "00:46", lyric: "或许注定了一生不分离"},
            {time: "00:53", lyric: "这是定夺了一生的意义"},
            {time: "01:19", lyric: "可你却转眼说要忘记"},
            {time: "01:26", lyric: "为什么你会忍心"},
            {time: "01:33", lyric: "抛下后离开"},
            {time: "01:45", lyric: "付出太多换来是什么"},
            {time: "01:52", lyric: "最终还要承受着寂寞"},
            {time: "02:04", lyric: "为什么你会忍心"},
            {time: "02:10", lyric: "真心全都给你"},
            {time: "02:17", lyric: "未来生活我不求什么"},
            {time: "02:22", lyric: "只想快乐"},
            {time: "02:45", lyric: "快乐"},
            {time: "05:52", lyric: "一切让我们奇迹相遇"},
            {time: "03:04", lyric: "这就注定了我们的缘分"},
            {time: "03:10", lyric: "所有的秘密都是情意"},
            {time: "03:17", lyric: "就不能荒谬的忘记"},
            {time: "03:22", lyric: "一切安排了我再见到你"},
            {time: "03:25", lyric: "或许注定了一生不分离"},
            {time: "03:31", lyric: "这是定夺了一生的意义"},
            {time: "03:37", lyric: "可你却转眼说要忘记"},
            {time: "03:42", lyric: "为什么你会忍心"},
            {time: "03:45", lyric: "抛下后离开"},
            {time: "03:52", lyric: "付出太多换来是什么"},
            {time: "03:57", lyric: "最终还要承受着寂寞"},
            {time: "04:02", lyric: "为什么你会忍心"},
            {time: "04:08", lyric: "真心全都给你"},
            {time: "04:15", lyric: "未来生活我不求什么"},
            {time: "04:22", lyric: "只想快乐"},
            {time: "04:28", lyric: "快乐"},
            {time: "04:35", lyric: "互换情报的重要"},
            {time: "04:42", lyric: "开始心荡神摇"},
            {time: "04:48", lyric: "别倒头睡着"},
            {time: "04:53", lyric: "你的美我全部都知道"},
            {time: "05:00", lyric: "像微笑痛苦的烦恼"},
            {time: "05:03", lyric: "昨日的情缘不能再了"},
            {time: "05:09", lyric: "回首舍不得"},
            {time: "05:14", lyric: "需要的好"},
            {time: "05:19", lyric: "你的美我全部都知道"},
            {time: "05:25", lyric: "像微笑痛苦的烦恼"},
            {time: "05:30", lyric: "回首舍不得"}
            
        ]
    },
    {
        id: "29",
        songs: "爱的甜蜜",
        name: "杨睿",
        src: "music/爱的甜蜜.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "这个味道 只有你做到"},
            {time: "00:20", lyric: "马上扔下皮包 把你找"},
            {time: "00:27", lyric: "你一定是 在厨房中用心炸烹"},
            {time: "00:33", lyric: "每次这时 心里很激动"},
            {time: "00:40", lyric: "你回来时一直都这样"},
            {time: "00:46", lyric: "走进厨房 作我爱吃的菜与汤"},
            {time: "00:53", lyric: "这特殊的关爱不会忘"},
            {time: "01:19", lyric: "一直在延续"},
            {time: "01:26", lyric: "馨香之气弥漫回忆里"},
            {time: "01:33", lyric: "爱在厨房里"},
            {time: "01:45", lyric: "感谢你给我特殊情谊"},
            {time: "01:52", lyric: "爱在厨房里"},
            {time: "02:04", lyric: "饭菜中吃出爱的甜蜜"},
           
            
        ]
    },
    {
        id: "30",
        songs: "爱的心没改变",
        name: "杨睿",
        src: "music/爱的心没改变.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "走在海边天空有些阴暗"},
            {time: "00:20", lyric: "望向远方看淡一片蔚蓝"},
            {time: "00:27", lyric: "习惯地看看右边"},
            {time: "00:33", lyric: "只有沙滩光秃一片"},
            {time: "00:40", lyric: "又回想起两年前的海边"},
            {time: "00:46", lyric: "眼前浮现你的笑语欢颜"},
            {time: "00:53", lyric: "意想不到的转变"},
            {time: "01:19", lyric: "陪你走完最后的时间"},
            {time: "01:26", lyric: "爱的心没改变"},
            {time: "01:33", lyric: "梦的事没做完"},
            {time: "01:45", lyric: "不会忘记你最后的祝愿"},
            {time: "01:52", lyric: "爱的心没改变"},
            {time: "02:04", lyric: "梦的事没做完"},
            {time: "02:10", lyric: "你的灵魂会永远陪在我身边"}
           
            
        ]
    },
    {
        id: "31",
        songs: "爱的转折点",
        name: "杨睿",
        src: "music/爱的转折点.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "爱的转折点"},
            {time: "00:20", lyric: "你能不能够看见"},
            {time: "00:27", lyric: "爱的事里面"},
            {time: "00:33", lyric: "似乎不都那么简单"},
            {time: "00:40", lyric: "见过第一眼"},
            {time: "00:46", lyric: "心里有了一个判断"},
            {time: "00:53", lyric: "但是人的特质完全表现需要时间"},
            {time: "01:19", lyric: "是不是有缘"},
            {time: "01:26", lyric: "不能够完全取决于第一眼"},
            {time: "01:33", lyric: "有了相处的时间"},
            {time: "01:45", lyric: "才能互相了解多一点"},
            {time: "01:52", lyric: "如今的年代"},
            {time: "02:04", lyric: "不知人们需要怎样的爱"},
            {time: "02:10", lyric: "自己需要明白"},
            {time: "02:17", lyric: "爱的转折点"},
            {time: "02:22", lyric: "你能不能够看见"},
            {time: "02:45", lyric: "爱的事里面"},
            {time: "05:52", lyric: "一切让我们似乎不都那么简单奇迹相遇"},
            
        ]
    },
    {
        id: "32",
        songs: "不在错过",
        name: "杨睿",
        src: "music/不再错过.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "在手机里面 两份邀请的来电"},
            {time: "00:20", lyric: "真没有想到 还要做这样的选择"},
            {time: "00:27", lyric: "工作的繁忙 让我暂忘约会姑娘"},
            {time: "00:33", lyric: "全部都错过"},
            {time: "00:40", lyric: "每次面对约会 心中总会感觉有些怯懦"},
            {time: "00:46", lyric: "人的信任那么脆弱"},
            {time: "00:53", lyric: "不知道该说些什么 不知该怎么说"},
            {time: "01:19", lyric: "错过 错过 很想改变不再错过"},
           
            
        ]
    },
    {
        id: "33",
        songs: "秋风阵阵",
        name: "杨睿",
        src: "music/秋风阵阵.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "秋风阵阵催着冬天"},
            {time: "00:20", lyric: "百无聊赖卷起了珠帘"},
            {time: "00:27", lyric: "黄叶飘落夕阳已晚"},
            {time: "00:33", lyric: "萧杀破败悲伤无限"},
            {time: "00:40", lyric: "黄叶铺满龟裂大地"},
            {time: "00:46", lyric: "楼下花轿枝头喜鹊报喜"},
            {time: "00:53", lyric: "红色帷幔增添些生气"},
            {time: "01:19", lyric: "与秋之凄成对比"},
            {time: "01:26", lyric: "湖水映天成碧绿"},
            {time: "01:33", lyric: "云朵更飘逸"},
            {time: "01:45", lyric: "彷佛五彩国画里"},
            {time: "01:52", lyric: "独特的美丽"},
            {time: "02:04", lyric: "这碧云天和黄叶地"},
            {time: "02:10", lyric: "秋日塑造这个一黄一绿"},
            {time: "02:17", lyric: "风吹湖面涟漪渐起"},
            {time: "02:22", lyric: "这幅画有了活力"},
           
            
        ]
    },
    {
        id: "34",
        songs: "人生的追求",
        name: "杨睿",
        src: "music/人生的追求.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "一直再重复"},
            {time: "00:20", lyric: "多年同样的脚步"},
            {time: "00:27", lyric: "坚持着没有服输"},
            {time: "00:33", lyric: "熬字当头"},
            {time: "00:40", lyric: "年年回首"},
            {time: "00:46", lyric: "不知何日能熬出头"},
            {time: "00:53", lyric: "战场需要坚守"},
            {time: "01:19", lyric: "坚守也是我人生的追求"},
            {time: "01:26", lyric: "一年又到头"},
            {time: "01:33", lyric: "路在坚持走"},
            {time: "01:45", lyric: "找不出一个放弃理由"},
            {time: "01:52", lyric: "熬的时候不只是有烦忧"},
            {time: "02:04", lyric: "不知熬的路途有没有尽头"},
            {time: "02:10", lyric: "不会低头"},
            {time: "02:17", lyric: "一直再重复"},
            {time: "02:22", lyric: "多年同样的脚步"},
            {time: "02:45", lyric: "坚持着没有服输"},
            {time: "05:52", lyric: "熬字当头"},
            
        ]
    },
    {
        id: "35",
        songs: "想念的家",
        name: "杨睿",
        src: "music/想念的家.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "家 马上就要出现在眼前啦"},
            {time: "00:20", lyric: "加快了脚步 心里响起了欢呼"},
            {time: "00:27", lyric: "看 大门外那是爸妈的身影"},
            {time: "00:33", lyric: "激动地心情 随着泪水宣泄着"},
            {time: "00:40", lyric: "我又回来啦 我想念的家"},
            {time: "00:46", lyric: "漫长等待与亲人再团圆"},
            {time: "00:53", lyric: "我又回来啦 我想念的家"},
            {time: "01:19", lyric: "说说心里话看看家的变化"},
            {time: "01:26", lyric: "家 一辈子永远都会牵挂它"},
            {time: "01:33", lyric: "梦在心里面 还有亲人笑语欢颜"},
           
            
        ]
    },
    {
        id: "36",
        songs: "学会解脱",
        name: "杨睿",
        src: "music/学会解脱.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "你有多少的困惑"},
            {time: "00:20", lyric: "你有多少的收获"},
            {time: "00:27", lyric: "这年纪是否学会解脱"},
            {time: "00:33", lyric: "经历了坎坷挫折"},
            {time: "00:40", lyric: "人生进入了不惑"},
            {time: "00:46", lyric: "心不再随便为谁停泊"},
            {time: "00:53", lyric: "明白什么会属于我"},
            {time: "01:19", lyric: "但还有困惑"},
            {time: "01:26", lyric: "你的心里想些什么 是错是对 不会说"},
            {time: "01:33", lyric: "不会偏离已有的品格"},
            {time: "01:45", lyric: "保持住自我"},
            {time: "01:52", lyric: "知道如何好好过活 是真是假 会辩驳"},
            {time: "02:04", lyric: "你有多少的困惑"},
            {time: "02:10", lyric: "你有多少的收获"},
        
        ]
    },
    {
        id: "37",
        songs: "一起流浪",
        name: "杨睿",
        src: "music/一起流浪.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "我们反着穿上情侣装"},
            {time: "00:20", lyric: "歪歪地戴上了棒球帽"},
            {time: "00:27", lyric: "还有一个大大眼镜框"},
            {time: "00:33", lyric: "一起骑着车去流浪"},
            {time: "00:40", lyric: "怪异的目光 落在 我们身上"},
            {time: "00:46", lyric: "我们两个只是笑得很夸张"},
            {time: "00:53", lyric: "奇怪的装扮 我们的时尚"},
            {time: "01:19", lyric: "这就是我们爱的模样"},
            {time: "01:26", lyric: "一起去搞怪流浪"},
            {time: "01:33", lyric: "一起在大海上飘荡"},
           
            
        ]
    },
    {
        id: "38",
        songs: "雨季的歌",
        name: "杨睿",
        src: "music/雨季的歌.mp3",
        alltime: "02:14",
        photo: "../img/chun2.png",
        lyrics: [
            
            {time: "00:13", lyric: "哗窗外的雨唱起了它的歌"},
            {time: "00:20", lyric: "我望着外面期盼着"},
            {time: "00:27", lyric: "她曾说今天是个特殊日子"},
            {time: "00:33", lyric: "会有惊喜的"},
            {time: "00:40", lyric: "雨伞朵朵"},
            {time: "00:46", lyric: "你会是哪一个"},
            {time: "00:53", lyric: "手中也许会拿些什么"},
            {time: "01:19", lyric: "担心你会在这雨天淋湿了"},
            {time: "01:26", lyric: "门铃在我期待中响了"},
            {time: "01:33", lyric: "你还在气喘着"},
            {time: "01:45", lyric: "第一反应抱你入怀中"},
            
            
        ]
    }
]
